import React from 'react';
import './ContentSections.css';

export default function ContentSections() {
  return (
    <div className="content-container">
      <section className="section about-section" id="operations">
        <div className="section-content">
          <div className="text-content">
            <h3 className="section-subtitle">ABOUT US</h3>
            <h2 className="section-title">Master the Markets with Professional Guidance</h2>
            <p>
              At Market Investopedia, we believe that informed traders are successful traders. 
              Our comprehensive educational programs are designed to take you from a beginner 
              to an advanced market analyst.
            </p>
            <ul className="feature-list">
              <li>✓ Live Trading Sessions</li>
              <li>✓ 1-on-1 Mentorship</li>
              <li>✓ Advanced Technical Analysis</li>
            </ul>
            <button className="btn btn-primary mt-4">Learn More</button>
          </div>
          <div className="image-content bg-placeholder-1">
            {/* Placeholder for an image */}
          </div>
        </div>
      </section>

      <section className="section services-section bg-light" id="market-signals">
        <div className="section-content flex-reverse">
          <div className="text-content">
            <h3 className="section-subtitle">OUR SERVICES</h3>
            <h2 className="section-title">Premium Market Signals</h2>
            <p>
              Get access to our elite market signals generated by years of experience and 
              deep market analysis. We cover Forex, Crypto, and Commodities.
            </p>
            <div className="services-grid">
              <div className="service-card">
                <h4>Forex Trading</h4>
                <p>Major, minor and exotic pairs analysis.</p>
              </div>
              <div className="service-card">
                <h4>Crypto Assets</h4>
                <p>Bitcoin, Ethereum and altcoin setups.</p>
              </div>
            </div>
          </div>
          <div className="image-content bg-placeholder-2">
            {/* Placeholder for an image */}
          </div>
        </div>
      </section>
    </div>
  );
}
